services:
  ml_cuda:
    build: .
    volumes:
    - ./model:/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
